name: Docker Image CI

on:
  push:
    branches: [ "master", "feature-docker" ]
  pull_request:
    branches: [ "master", "feature-docker" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file docker/DockerfileMultistageBuild --tag o4xp:$(date +%s)
